version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.9
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: react-intl
    versions:
    - 5.11.0
    - 5.8.0
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: sass-loader
    versions:
    - 10.1.0
    - 10.1.1
  - dependency-name: typescript
    versions:
    - 4.1.2
    - 4.1.3
  - dependency-name: webpack
    versions:
    - 5.11.1
  - dependency-name: "@storybook/addon-storysource"
    versions:
    - 6.1.11
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.166
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
  - dependency-name: ts-loader
    versions:
    - 8.0.13
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.2
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: "@types/react-test-renderer"
    versions:
    - 17.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.1.0
  - dependency-name: "@types/react"
    versions:
    - 16.9.55
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@material-ui/icons"
    versions:
    - 4.9.1
  - dependency-name: ts-jest
    versions:
    - 24.3.0
  - dependency-name: "@types/react-redux"
    versions:
    - 7.1.9
  - dependency-name: "@types/react-transition-group"
    versions:
    - 4.4.0
  - dependency-name: cross-env
    versions:
    - 7.0.2
