import { MetaDataMap } from './MetaData';

export default {
  Equipment: {
    extends: 'Item',
    LocalStats: {},
    Mods: {
      stat_description_list: ['Metadata/stat_descriptions.txt'],
      enable_rarity: ['normal', 'magic', 'rare', 'unique'],
    },
    inheritance: ['Item', 'Equipment'],
    tags: ['default'],
  },
  Item: {
    extends: 'nothing',
    Base: { base_level: ['1\r'], tag: ['default'] },
    inheritance: ['Item'],
    tags: ['default'],
  },
  AbstractAmulet: {
    extends: 'Equipment',
    Base: { x_size: ['1\r'], y_size: ['1\r'], tag: ['amulet'] },
    Mods: { inventory_type: ['Amulet'] },
    inheritance: ['Item', 'Equipment', 'AbstractAmulet'],
    tags: ['default', 'amulet'],
  },
  AbstractSocketableAmulet: {
    extends: 'AbstractAmulet',
    AttributeRequirements: {
      strength_requirement: ['0\r'],
      dexterity_requirement: ['0\r'],
      intelligence_requirement: ['0\r'],
    },
    Sockets: {
      socket_info: [
        '0:1:1 1:9999:100 2:9999:90 3:9999:80 4:9999:30 5:9999:20 6:9999:5',
      ],
    },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractAmulet',
      'AbstractSocketableAmulet',
    ],
    tags: ['default', 'amulet'],
  },
  Talisman1_1: {
    extends: 'AbstractSocketableAmulet',
    inheritance: [
      'Item',
      'Equipment',
      'AbstractAmulet',
      'AbstractSocketableAmulet',
      'Talisman1_1',
    ],
    tags: ['default', 'amulet'],
  },
  Talisman4: {
    extends: 'AbstractSocketableAmulet',
    inheritance: [
      'Item',
      'Equipment',
      'AbstractAmulet',
      'AbstractSocketableAmulet',
      'Talisman4',
    ],
    tags: ['default', 'amulet'],
  },
  AbstractArmour: {
    extends: 'Equipment',
    Base: { tag: ['armour'] },
    Quality: { max_quality: ['20\r'] },
    Sockets: {
      socket_info: ['1:1:100 2:1:90 3:2:80 4:25:30 5:9999:20 6:9999:5'],
    },
    inheritance: ['Item', 'Equipment', 'AbstractArmour'],
    tags: ['default', 'armour'],
  },
  AbstractBodyArmour: {
    extends: 'AbstractArmour',
    Base: { tag: ['body_armour'] },
    Mods: { inventory_type: ['BodyArmour'] },
    Sockets: {
      socket_info: ['1:1:50 2:1:120 3:2:100 4:25:30 5:35:5 6:50:1'],
    },
    inheritance: ['Item', 'Equipment', 'AbstractArmour', 'AbstractBodyArmour'],
    tags: ['default', 'armour', 'body_armour'],
  },
  AbstractBoots: {
    extends: 'AbstractArmour',
    Base: { x_size: ['2\r'], y_size: ['2\r'], tag: ['boots'] },
    Mods: { inventory_type: ['Boots'] },
    inheritance: ['Item', 'Equipment', 'AbstractArmour', 'AbstractBoots'],
    tags: ['default', 'armour', 'boots'],
  },
  AbstractGloves: {
    extends: 'AbstractArmour',
    Base: { x_size: ['2\r'], y_size: ['2\r'], tag: ['gloves'] },
    Mods: { inventory_type: ['Gloves'] },
    inheritance: ['Item', 'Equipment', 'AbstractArmour', 'AbstractGloves'],
    tags: ['default', 'armour', 'gloves'],
  },
  AbstractHelmet: {
    extends: 'AbstractArmour',
    Base: { x_size: ['2\r'], y_size: ['2\r'], tag: ['helmet'] },
    Mods: { inventory_type: ['Helm'] },
    inheritance: ['Item', 'Equipment', 'AbstractArmour', 'AbstractHelmet'],
    tags: ['default', 'armour', 'helmet'],
  },
  AbstractShield: {
    extends: 'AbstractArmour',
    Base: { x_size: ['2\r'], y_size: ['2\r'], tag: ['shield'] },
    Shield: { block_percentage: ['0\r'] },
    Mods: { inventory_type: ['Offhand'] },
    Sockets: {
      socket_info: ['1:1:50 2:1:120 3:2:100 4:9999:30 5:9999:20 6:9999:5'],
    },
    inheritance: ['Item', 'Equipment', 'AbstractArmour', 'AbstractShield'],
    tags: ['default', 'armour', 'shield'],
  },
  AbstractBelt: {
    extends: 'Equipment',
    Base: { x_size: ['2\r'], y_size: ['1\r'], tag: ['belt'] },
    Mods: { inventory_type: ['Belt'] },
    inheritance: ['Item', 'Equipment', 'AbstractBelt'],
    tags: ['default', 'belt'],
  },
  AbstractCurrency: {
    extends: 'Item',
    Base: { x_size: ['1\r'], y_size: ['1\r'] },
    inheritance: ['Item', 'AbstractCurrency'],
    tags: ['default'],
  },
  AbstractMicrotransaction: {
    extends: 'AbstractCurrency',
    Stack: {},
    inheritance: ['Item', 'AbstractCurrency', 'AbstractMicrotransaction'],
    tags: ['default'],
  },
  CurrencyImprint: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'CurrencyImprint',
    ],
    tags: ['default', 'currency'],
  },
  StackableCurrency: {
    extends: 'AbstractCurrency',
    Base: { tag: ['currency'] },
    Stack: {},
    inheritance: ['Item', 'AbstractCurrency', 'StackableCurrency'],
    tags: ['default', 'currency'],
  },
  AbstractDivinationCard: {
    extends: 'Item',
    Base: {
      x_size: ['1\r'],
      y_size: ['1\r'],
      tag: ['divination_card'],
    },
    Stack: {},
    inheritance: ['Item', 'AbstractDivinationCard'],
    tags: ['default', 'divination_card'],
  },
  AbstractFlask: {
    extends: 'Item',
    Base: {
      tag: ['flask'],
      x_size: ['1\r'],
      y_size: ['2\r'],
      description_text: ['ItemDescriptionFlask'],
    },
    Quality: { max_quality: ['20\r'] },
    LocalStats: {},
    Charges: { max_charges: ['2\t\r'] },
    Mods: {
      stat_description_list: ['Metadata/stat_descriptions.txt'],
      enable_rarity: ['normal', 'magic', 'unique'],
      disable_rarity: ['rare'],
      inventory_type: ['Flask'],
    },
    Usable: { use_type: ['Usable'], action: ['flask'] },
    Imprint: {},
    inheritance: ['Item', 'AbstractFlask'],
    tags: ['default', 'flask'],
  },
  AbstractHybridFlask: {
    extends: 'AbstractFlask',
    Base: { tag: ['hybrid_flask'] },
    inheritance: ['Item', 'AbstractFlask', 'AbstractHybridFlask'],
    tags: ['default', 'flask', 'hybrid_flask'],
  },
  AbstractLifeFlask: {
    extends: 'AbstractFlask',
    Base: { tag: ['life_flask'] },
    inheritance: ['Item', 'AbstractFlask', 'AbstractLifeFlask'],
    tags: ['default', 'flask', 'life_flask'],
  },
  AbstractManaFlask: {
    extends: 'AbstractFlask',
    Base: { tag: ['mana_flask'] },
    inheritance: ['Item', 'AbstractFlask', 'AbstractManaFlask'],
    tags: ['default', 'flask', 'mana_flask'],
  },
  AbstractUtilityFlask: {
    extends: 'AbstractFlask',
    Base: { tag: ['utility_flask'] },
    inheritance: ['Item', 'AbstractFlask', 'AbstractUtilityFlask'],
    tags: ['default', 'flask', 'utility_flask'],
  },
  CriticalUtilityFlask: {
    extends: 'AbstractUtilityFlask',
    Base: { tag: ['critical_utility_flask'] },
    inheritance: [
      'Item',
      'AbstractFlask',
      'AbstractUtilityFlask',
      'CriticalUtilityFlask',
    ],
    tags: ['default', 'flask', 'utility_flask', 'critical_utility_flask'],
  },
  FlaskUtility1: {
    extends: 'AbstractUtilityFlask',
    Base: { description_text: ['ItemDescriptionFlaskUtility1'] },
    inheritance: [
      'Item',
      'AbstractFlask',
      'AbstractUtilityFlask',
      'FlaskUtility1',
    ],
    tags: ['default', 'flask', 'utility_flask'],
  },
  AbstractSkillGem: {
    extends: 'Item',
    Base: {
      tag: ['gem'],
      x_size: ['1\r'],
      y_size: ['1\r'],
      description_text: ['ItemDescriptionSkillGem'],
    },
    SkillGem: {},
    Quality: { max_quality: ['20\r'] },
    inheritance: ['Item', 'AbstractSkillGem'],
    tags: ['default', 'gem'],
  },
  ActiveSkillGem: {
    extends: 'AbstractSkillGem',
    Base: { description_text: ['ItemDescriptionActiveSkillGem'] },
    SkillGem: {},
    inheritance: ['Item', 'AbstractSkillGem', 'ActiveSkillGem'],
    tags: ['default', 'gem'],
  },
  SupportSkillGem: {
    extends: 'AbstractSkillGem',
    Base: {
      description_text: ['ItemDescriptionSupportSkillGem'],
      tag: ['support_gem'],
    },
    SkillGem: {},
    inheritance: ['Item', 'AbstractSkillGem', 'SupportSkillGem'],
    tags: ['default', 'gem', 'support_gem'],
  },
  AbstractHideoutDoodad: {
    extends: 'Item',
    Base: { x_size: ['1\r'], y_size: ['1\r'] },
    Stack: {},
    inheritance: ['Item', 'AbstractHideoutDoodad'],
    tags: ['default'],
  },
  AbstractJewel: {
    extends: 'Item',
    Base: {
      x_size: ['1\r'],
      y_size: ['1\r'],
      description_text: ['ItemDescriptionPassiveJewel'],
    },
    LocalStats: {},
    Mods: {
      stat_description_list: ['Metadata/stat_descriptions.txt'],
      enable_rarity: ['magic', 'rare', 'unique'],
      inventory_type: ['passivejewels'],
    },
    inheritance: ['Item', 'AbstractJewel'],
    tags: ['default'],
  },
  AbstractLabyrinthItem: {
    extends: 'Item',
    Stack: { max_stack_size: ['1\r'] },
    inheritance: ['Item', 'AbstractLabyrinthItem'],
    tags: ['default'],
  },
  BronzeKey: {
    extends: 'AbstractLabyrinthItem',
    Base: { description_text: ['TreasureKeyDescription'] },
    inheritance: ['Item', 'AbstractLabyrinthItem', 'BronzeKey'],
    tags: ['default'],
  },
  GoldenKey: {
    extends: 'AbstractLabyrinthItem',
    Base: { description_text: ['GoldenKeyDescription'] },
    inheritance: ['Item', 'AbstractLabyrinthItem', 'GoldenKey'],
    tags: ['default'],
  },
  LabyrinthTrinket: {
    extends: 'AbstractLabyrinthItem',
    Base: { x_size: ['1\r'], y_size: ['1\r'] },
    inheritance: ['Item', 'AbstractLabyrinthItem', 'LabyrinthTrinket'],
    tags: ['default'],
  },
  SilverKey: {
    extends: 'AbstractLabyrinthItem',
    Base: { description_text: ['SilverKeyDescription'] },
    inheritance: ['Item', 'AbstractLabyrinthItem', 'SilverKey'],
    tags: ['default'],
  },
  AbstractMapFragment: {
    extends: 'Item',
    Base: { description_text: ['ItemDescriptionMapFragment'] },
    LocalStats: {},
    Mods: {
      stat_description_list: ['Metadata/stat_descriptions.txt'],
      inventory_type: ['Map'],
    },
    inheritance: ['Item', 'AbstractMapFragment'],
    tags: ['default'],
  },
  AbstractMap: {
    extends: 'Equipment',
    Base: { tag: ['map'], description_text: ['ItemDescriptionMap'] },
    LocalStats: {},
    Mods: {},
    Quality: { max_quality: ['20\r'] },
    Map: {},
    inheritance: ['Item', 'Equipment', 'AbstractMap'],
    tags: ['default', 'map'],
  },
  MysteryBox1x1: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'MysteryBox1x1',
    ],
    tags: ['default', 'currency'],
  },
  MysteryBox1x2: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'MysteryBox1x2',
    ],
    tags: ['default', 'currency'],
  },
  MysteryBox1x3: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'MysteryBox1x3',
    ],
    tags: ['default', 'currency'],
  },
  MysteryBox1x4: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'MysteryBox1x4',
    ],
    tags: ['default', 'currency'],
  },
  MysteryBox2x1: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'MysteryBox2x1',
    ],
    tags: ['default', 'currency'],
  },
  MysteryBox2x2: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'MysteryBox2x2',
    ],
    tags: ['default', 'currency'],
  },
  MysteryBox2x3: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'MysteryBox2x3',
    ],
    tags: ['default', 'currency'],
  },
  MysteryBox2x4: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'MysteryBox2x4',
    ],
    tags: ['default', 'currency'],
  },
  MysteryBox3x2: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'MysteryBox3x2',
    ],
    tags: ['default', 'currency'],
  },
  MysteryBox3x3: {
    extends: 'StackableCurrency',
    Imprint: {},
    inheritance: [
      'Item',
      'AbstractCurrency',
      'StackableCurrency',
      'MysteryBox3x3',
    ],
    tags: ['default', 'currency'],
  },
  AbstractQuestItem: {
    extends: 'Item',
    Base: { x_size: ['1\r'], y_size: ['1\r'] },
    Quest: {},
    inheritance: ['Item', 'AbstractQuestItem'],
    tags: ['default'],
  },
  AllFlameLantern1: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a1q6minusHaveAllFlame'],
      remove_flag: ['a1q6minusDeliveredAllFlame'],
    },
    inheritance: ['Item', 'AllFlameLantern1'],
    tags: ['default'],
  },
  GoldenHand: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a2q5minusHaveGoldenHand'],
      remove_flag: ['a2q5minusDeliveredGoldenHand'],
      extra_flag: ['a2q5minusReceivedQuest'],
    },
    inheritance: ['Item', 'GoldenHand'],
    tags: ['default'],
  },
  InfernalTalc: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q5minusHaveTalc'],
      remove_flag: ['a3q5minusUsedTalc'],
    },
    inheritance: ['Item', 'InfernalTalc'],
    tags: ['default'],
  },
  MedicineSet1: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a1q5minusHaveMedicineChest'],
      remove_flag: ['a1q5minusNessaCongratulated'],
      extra_flag: ['SeenMedicineChest'],
    },
    inheritance: ['Item', 'MedicineSet1'],
    tags: ['default'],
  },
  PoisonSkillGem: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a2q6minusHaveSkillGem'],
      remove_flag: ['a2q9minusPoisonedTree'],
      extra_flag: ['a2q6minusHelenaInTown'],
      extra_flag2: ['SeenBalefulGem'],
    },
    inheritance: ['Item', 'PoisonSkillGem'],
    tags: ['default'],
  },
  PoisonSpear: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a2q4minusHavePoisonSpear'],
      remove_flag: ['a2q9minusPoisonedTree'],
      extra_flag: ['a2q4minusReceivedQuest'],
      extra_flag2: ['a2bminusStartNewQuests'],
    },
    inheritance: ['Item', 'PoisonSpear'],
    tags: ['default'],
  },
  RibbonSpool: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q4minusHaveRibbonSpool'],
      remove_flag: ['a3q4minusDeliveredSpool'],
      extra_flag: ['SeenRibbonSpool'],
    },
    inheritance: ['Item', 'RibbonSpool'],
    tags: ['default'],
  },
  SewerKeys: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q11minusHaveSewerKeys'],
      remove_flag: ['a3q11minusUsedSewerKeys'],
    },
    inheritance: ['Item', 'SewerKeys'],
    tags: ['default'],
  },
  SpikeSealKey: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a2q11minusHaveKey'],
      remove_flag: ['a1q9minusRoadOpened'],
      extra_flag: ['a2q11minusSeenKey'],
      extra_flag2: ['a1q9minusRoadBlocked'],
    },
    inheritance: ['Item', 'SpikeSealKey'],
    tags: ['default'],
  },
  SulphiteFlask: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q5minusHaveSulphite'],
      remove_flag: ['a3q5minusDeliveredSulphite'],
      extra_flag: ['SeenSulphite'],
    },
    inheritance: ['Item', 'SulphiteFlask'],
    tags: ['default'],
  },
  TolmanBracelet: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q2minusHaveTolmanItem'],
      remove_flag: ['a3q2minusDeliveredItem'],
      extra_flag: ['a3q2minusSeenTolmanItem'],
    },
    inheritance: ['Item', 'TolmanBracelet'],
    tags: ['default'],
  },
  TowerKey: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q9minusHaveTowerKey'],
      remove_flag: ['a3q9minusUsedTowerKey'],
      extra_flag: ['SeenTowerKey'],
    },
    inheritance: ['Item', 'TowerKey'],
    tags: ['default'],
  },
  'Book-a4q6': {
    extends: 'AbstractQuestItem',
    Base: {
      description_text: [
        'ItemDescriptionBookPassivePointAnd2RespecPointsTasuni',
      ],
    },
    Quest: {
      use_flag: ['a4q6minusUsedRewardBook'],
      grant_flag: ['a4q6minusHaveRewardBook'],
      remove_flag: ['a4q6minusUsedRewardBook'],
      respec_points: ['2\r'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionPassivePointAnd2RespecPoints'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Book-a4q6'],
    tags: ['default'],
  },
  DaressoGem: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a4q4minusHaveGem'],
      remove_flag: ['a4q4minusDeliveredGem'],
      extra_flag: ['a4q1minusGemQuestsReceived'],
    },
    inheritance: ['Item', 'DaressoGem'],
    tags: ['default'],
  },
  KaomGem: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a4q3minusHaveGem'],
      remove_flag: ['a4q3minusDeliveredGem'],
      extra_flag: ['a4q1minusGemQuestsReceived'],
    },
    inheritance: ['Item', 'KaomGem'],
    tags: ['default'],
  },
  Organ1: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a4q5minusHaveOrgan1'],
      remove_flag: ['a4q5minusDeliveredOrgan1'],
      extra_flag: ['a4q5minusSeenOrgan'],
    },
    inheritance: ['Item', 'Organ1'],
    tags: ['default'],
  },
  Organ2: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a4q5minusHaveOrgan2'],
      remove_flag: ['a4q5minusDeliveredOrgan2'],
      extra_flag: ['a4q5minusSeenOrgan'],
    },
    inheritance: ['Item', 'Organ2'],
    tags: ['default'],
  },
  Organ3: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a4q5minusHaveOrgan3'],
      remove_flag: ['a4q5minusDeliveredOrgan3'],
      extra_flag: ['a4q5minusSeenOrgan'],
    },
    inheritance: ['Item', 'Organ3'],
    tags: ['default'],
  },
  RedBanner: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a4q2minusHaveBanner'],
      remove_flag: ['a4q2minusUsedBanner'],
      extra_flag: ['a4q2minusQuestReceived'],
    },
    inheritance: ['Item', 'RedBanner'],
    tags: ['default'],
  },
  CombinedAmulet: {
    extends: 'Item',
    Quest: {
      remove_flag: ['a2q8minusPlacedApex'],
      grant_flag: ['a2q8minusHaveApex'],
    },
    inheritance: ['Item', 'CombinedAmulet'],
    tags: ['default'],
  },
  DexAmulet: {
    extends: 'Item',
    Quest: {
      remove_flag: ['a2bminusDeliveredAmulets'],
      grant_flag: ['a2bminusHaveDexAmulet'],
      extra_flag: ['a2bminusKilledDexBandit'],
    },
    inheritance: ['Item', 'DexAmulet'],
    tags: ['default'],
  },
  IntAmulet: {
    extends: 'Item',
    Quest: {
      remove_flag: ['a2bminusDeliveredAmulets'],
      grant_flag: ['a2bminusHaveIntAmulet'],
      extra_flag: ['a2bminusKilledIntBandit'],
    },
    inheritance: ['Item', 'IntAmulet'],
    tags: ['default'],
  },
  StrAmulet: {
    extends: 'Item',
    Quest: {
      remove_flag: ['a2bminusDeliveredAmulets'],
      grant_flag: ['a2bminusHaveStrAmulet'],
      extra_flag: ['a2bminusKilledStrBandit'],
    },
    inheritance: ['Item', 'StrAmulet'],
    tags: ['default'],
  },
  Bust1: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q11minusHaveBust1'],
      remove_flag: ['a3q11minusDeliveredBust1'],
      extra_flag: ['SeenBust1'],
    },
    inheritance: ['Item', 'Bust1'],
    tags: ['default'],
  },
  Bust2: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q11minusHaveBust2'],
      remove_flag: ['a3q11minusDeliveredBust2'],
      extra_flag: ['SeenBust2'],
    },
    inheritance: ['Item', 'Bust2'],
    tags: ['default'],
  },
  Bust3: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q11minusHaveBust3'],
      remove_flag: ['a3q11minusDeliveredBust3'],
      extra_flag: ['SeenBust3'],
    },
    inheritance: ['Item', 'Bust3'],
    tags: ['default'],
  },
  Decanter: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q13minusHaveDecanter'],
      remove_flag: ['a3q13minusDecanterDelivered'],
      extra_flag: ['SeenDecanter'],
    },
    inheritance: ['Item', 'Decanter'],
    tags: ['default'],
  },
  Fruit: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q13minusHavePlum'],
      remove_flag: ['a3q13minusPlumDelivered'],
      extra_flag: ['SeenPlum'],
    },
    inheritance: ['Item', 'Fruit'],
    tags: ['default'],
  },
  Glyph1: {
    extends: 'Item',
    Quest: {
      remove_flag: ['a1q4minusPlacedGlyphs'],
      grant_flag: ['a1q4minusHaveGlyph1'],
      extra_flag: ['a1q4minusKnowsAboutGlyphs'],
      extra_flag2: ['SeenShell1'],
    },
    inheritance: ['Item', 'Glyph1'],
    tags: ['default'],
  },
  Glyph2: {
    extends: 'Item',
    Quest: {
      remove_flag: ['a1q4minusPlacedGlyphs'],
      grant_flag: ['a1q4minusHaveGlyph2'],
      extra_flag: ['a1q4minusKnowsAboutGlyphs'],
      extra_flag2: ['SeenShell2'],
    },
    inheritance: ['Item', 'Glyph2'],
    tags: ['default'],
  },
  Glyph3: {
    extends: 'Item',
    Quest: {
      remove_flag: ['a1q4minusPlacedGlyphs'],
      grant_flag: ['a1q4minusHaveGlyph3'],
      extra_flag: ['a1q4minusKnowsAboutGlyphs'],
      extra_flag2: ['SeenShell3'],
    },
    inheritance: ['Item', 'Glyph3'],
    tags: ['default'],
  },
  Page1: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q12minusHavePage1'],
      extra_flag: ['a3q12minusSeenPages'],
      remove_flag: ['a3q12minusDeliveredPages'],
    },
    inheritance: ['Item', 'Page1'],
    tags: ['default'],
  },
  Page2: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q12minusHavePage2'],
      extra_flag: ['a3q12minusSeenPages'],
      remove_flag: ['a3q12minusDeliveredPages'],
    },
    inheritance: ['Item', 'Page2'],
    tags: ['default'],
  },
  Page3: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q12minusHavePage3'],
      extra_flag: ['a3q12minusSeenPages'],
      remove_flag: ['a3q12minusDeliveredPages'],
    },
    inheritance: ['Item', 'Page3'],
    tags: ['default'],
  },
  Page4: {
    extends: 'Item',
    Quest: {
      grant_flag: ['a3q12minusHavePage4'],
      extra_flag: ['a3q12minusSeenPages'],
      remove_flag: ['a3q12minusDeliveredPages'],
    },
    inheritance: ['Item', 'Page4'],
    tags: ['default'],
  },
  BanditRespecAlira: {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBanditRespecAlira'] },
    Quest: { can_sell: ['true\r'] },
    Usable: { action: ['respec_alira'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionBanditRespecAlira'] },
    inheritance: ['Item', 'AbstractQuestItem', 'BanditRespecAlira'],
    tags: ['default'],
  },
  BanditRespecEramir: {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBanditRespecEramir'] },
    Quest: { can_sell: ['true\r'] },
    Usable: { action: ['respec_eramir'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionBanditRespecEramir'] },
    inheritance: ['Item', 'AbstractQuestItem', 'BanditRespecEramir'],
    tags: ['default'],
  },
  BanditRespecKraityn: {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBanditRespecKraityn'] },
    Quest: { can_sell: ['true\r'] },
    Usable: { action: ['respec_kraityn'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionBanditRespecKraityn'] },
    inheritance: ['Item', 'AbstractQuestItem', 'BanditRespecKraityn'],
    tags: ['default'],
  },
  BanditRespecOak: {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBanditRespecOak'] },
    Quest: { can_sell: ['true\r'] },
    Usable: { action: ['respec_oak'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionBanditRespecOak'] },
    inheritance: ['Item', 'AbstractQuestItem', 'BanditRespecOak'],
    tags: ['default'],
  },
  'Book-a1q6': {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBookPassivePointBestel'] },
    Quest: {
      use_flag: ['a1q6minusUsedRewardBook'],
      grant_flag: ['a1q6minusHaveRewardBook'],
      remove_flag: ['a1q6minusUsedRewardBook'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionPassivePoint'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Book-a1q6'],
    tags: ['default'],
  },
  'Book-a1q7': {
    extends: 'AbstractQuestItem',
    Base: {
      description_text: ['ItemDescriptionBookPassivePointTarkleigh'],
    },
    Quest: {
      use_flag: ['a1q7minusUsedRewardBook'],
      grant_flag: ['a1q7minusHaveRewardBook'],
      remove_flag: ['a1q7minusUsedRewardBook'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionPassivePoint'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Book-a1q7'],
    tags: ['default'],
  },
  'Book-a1q8': {
    extends: 'AbstractQuestItem',
    Base: {
      description_text: ['ItemDescriptionBook2RespecPointsTarkleigh'],
    },
    Quest: {
      use_flag: ['a1q8minusUsedRewardBook'],
      grant_flag: ['a1q8minusHaveRewardBook'],
      remove_flag: ['a1q8minusUsedRewardBook'],
      respec_points: ['2\r'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunction2RespecPoints'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Book-a1q8'],
    tags: ['default'],
  },
  'Book-a1q9': {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBookPassivePointBestel'] },
    Quest: {
      use_flag: ['a1q9minusUsedRewardBook'],
      grant_flag: ['a1q9minusHaveRewardBook'],
      remove_flag: ['a1q9minusUsedRewardBook'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionPassivePoint'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Book-a1q9'],
    tags: ['default'],
  },
  'Book-a2q5': {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBook2RespecPointsYeena'] },
    Quest: {
      use_flag: ['a2q5minusUsedRewardBook'],
      grant_flag: ['a2q5minusHaveRewardBook'],
      remove_flag: ['a2q5minusUsedRewardBook'],
      respec_points: ['2\r'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunction2RespecPoints'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Book-a2q5'],
    tags: ['default'],
  },
  'Book-a3q11v0': {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBookPassivePointHargan'] },
    Quest: {
      use_flag: ['a3q11minusUsedRewardBook'],
      grant_flag: ['a3q11minusHaveRewardBook'],
      remove_flag: ['a3q11minusUsedRewardBook'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionPassivePoint'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Book-a3q11v0'],
    tags: ['default'],
  },
  'Book-a3q11v1': {
    extends: 'AbstractQuestItem',
    Base: {
      description_text: ['ItemDescriptionBookPassivePointAndRespecPointHargan'],
    },
    Quest: {
      use_flag: ['a3q11minusUsedRewardBook'],
      grant_flag: ['a3q11minusHaveRewardBook'],
      remove_flag: ['a3q11minusUsedRewardBook'],
      respec_points: ['1\r'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionPassivePointAndRespecPoint'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Book-a3q11v1'],
    tags: ['default'],
  },
  'Book-a3q11v2': {
    extends: 'AbstractQuestItem',
    Base: {
      description_text: [
        'ItemDescriptionBookPassivePointAnd2RespecPointsHargan',
      ],
    },
    Quest: {
      use_flag: ['a3q11minusUsedRewardBook'],
      grant_flag: ['a3q11minusHaveRewardBook'],
      remove_flag: ['a3q11minusUsedRewardBook'],
      respec_points: ['2\r'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunctionPassivePointAnd2RespecPoints'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Book-a3q11v2'],
    tags: ['default'],
  },
  'Book-a3q9': {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBook2PassivePointsGrigor'] },
    Quest: {
      use_flag: ['a3q9minusUsedRewardBook'],
      grant_flag: ['a3q9minusHaveRewardBook'],
      remove_flag: ['a3q9minusUsedRewardBook'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunction2PassivePoints'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Book-a3q9'],
    tags: ['default'],
  },
  Descent2_1: {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBook2PassivePoints'] },
    Quest: {
      use_flag: ['Descent2Reward1'],
      remove_flag: ['Descent2Reward1'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunction2PassivePoints'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Descent2_1'],
    tags: ['default'],
  },
  Descent2_2: {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBook2PassivePoints'] },
    Quest: {
      use_flag: ['Descent2Reward2'],
      remove_flag: ['Descent2Reward2'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunction2PassivePoints'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Descent2_2'],
    tags: ['default'],
  },
  Descent2_3: {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBook2PassivePoints'] },
    Quest: {
      use_flag: ['Descent2Reward3'],
      remove_flag: ['Descent2Reward3'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunction2PassivePoints'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Descent2_3'],
    tags: ['default'],
  },
  Descent2_4: {
    extends: 'AbstractQuestItem',
    Base: { description_text: ['ItemDescriptionBook2PassivePoints'] },
    Quest: {
      use_flag: ['Descent2Reward4'],
      remove_flag: ['Descent2Reward4'],
    },
    Usable: { action: ['skill_book'], use_type: ['Usable'] },
    Stack: { function_text: ['ItemFunction2PassivePoints'] },
    inheritance: ['Item', 'AbstractQuestItem', 'Descent2_4'],
    tags: ['default'],
  },
  AbstractQuiver: {
    extends: 'Equipment',
    Base: { tag: ['quiver'], x_size: ['2\r'], y_size: ['3\r'] },
    LocalStats: {},
    Mods: { inventory_type: ['Offhand'] },
    inheritance: ['Item', 'Equipment', 'AbstractQuiver'],
    tags: ['default', 'quiver'],
  },
  AbstractRelic: {
    extends: 'Equipment',
    Base: { tag: ['relic'] },
    LocalStats: {},
    Mods: {},
    inheritance: ['Item', 'Equipment', 'AbstractRelic'],
    tags: ['default', 'relic'],
  },
  AbstractLargeRelic: {
    extends: 'AbstractRelic',
    Base: { x_size: ['2\r'], y_size: ['2\r'] },
    LocalStats: {},
    Mods: { inventory_type: ['altar_large'] },
    inheritance: ['Item', 'Equipment', 'AbstractRelic', 'AbstractLargeRelic'],
    tags: ['default', 'relic'],
  },
  AbstractMediumRelic: {
    extends: 'AbstractRelic',
    Base: { x_size: ['1\r'], y_size: ['2\r'] },
    LocalStats: {},
    Mods: { inventory_type: ['altar_medium'] },
    inheritance: ['Item', 'Equipment', 'AbstractRelic', 'AbstractMediumRelic'],
    tags: ['default', 'relic'],
  },
  AbstractSmallRelic: {
    extends: 'AbstractRelic',
    Base: { x_size: ['1\r'], y_size: ['1\r'] },
    LocalStats: {},
    Mods: { inventory_type: ['altar_small'] },
    inheritance: ['Item', 'Equipment', 'AbstractRelic', 'AbstractSmallRelic'],
    tags: ['default', 'relic'],
  },
  AbstractRing: {
    extends: 'Equipment',
    Base: { x_size: ['1\r'], y_size: ['1\r'], tag: ['ring'] },
    Mods: { inventory_type: ['Ring'] },
    inheritance: ['Item', 'Equipment', 'AbstractRing'],
    tags: ['default', 'ring'],
  },
  AbstractSocketableRing: {
    extends: 'AbstractRing',
    AttributeRequirements: {
      strength_requirement: ['0\r'],
      dexterity_requirement: ['0\r'],
      intelligence_requirement: ['0\r'],
    },
    Sockets: {
      socket_info: [
        '0:1:1 1:9999:100 2:9999:90 3:9999:80 4:9999:30 5:9999:20 6:9999:5',
      ],
    },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractRing',
      'AbstractSocketableRing',
    ],
    tags: ['default', 'ring'],
  },
  Ring15: {
    extends: 'AbstractSocketableRing',
    inheritance: [
      'Item',
      'Equipment',
      'AbstractRing',
      'AbstractSocketableRing',
      'Ring15',
    ],
    tags: ['default', 'ring'],
  },
  AbstractWeapon: {
    extends: 'Equipment',
    AttributeRequirements: {
      strength_requirement: ['100\r'],
      dexterity_requirement: ['0\r'],
      intelligence_requirement: ['0\r'],
    },
    Mods: { inventory_type: ['Weapon"'] },
    Weapon: {
      minimum_attack_distance: ['0\r'],
      maximum_attack_distance: ['3\r'],
      minimum_damage: ['5\r'],
      maximum_damage: ['10\r'],
      weapon_speed: ['833\r'],
      critical_chance: ['500\r'],
      accuracy_rating: ['20\r'],
    },
    Quality: { max_quality: ['20\r'] },
    Base: { tag: ['weapon'] },
    Sockets: {
      socket_info: ['1:1:50 2:1:120 3:2:100 4:9999:30 5:9999:20 6:9999:5'],
    },
    inheritance: ['Item', 'Equipment', 'AbstractWeapon'],
    tags: ['default', 'weapon'],
  },
  AbstractOneHandWeapon: {
    extends: 'AbstractWeapon',
    Base: { tag: ['onehand'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractOneHandWeapon',
    ],
    tags: ['default', 'weapon', 'onehand'],
  },
  AbstractClaw: {
    extends: 'AbstractOneHandWeapon',
    Base: { tag: ['claw', 'one_hand_weapon'] },
    Weapon: { weapon_class: ['Claw'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractOneHandWeapon',
      'AbstractClaw',
    ],
    tags: ['default', 'weapon', 'onehand', 'claw', 'one_hand_weapon'],
  },
  AbstractDagger: {
    extends: 'AbstractOneHandWeapon',
    Base: { tag: ['dagger', 'one_hand_weapon'] },
    Weapon: { weapon_class: ['Dagger'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractOneHandWeapon',
      'AbstractDagger',
    ],
    tags: ['default', 'weapon', 'onehand', 'dagger', 'one_hand_weapon'],
  },
  AbstractOneHandAxe: {
    extends: 'AbstractOneHandWeapon',
    Base: { tag: ['axe', 'one_hand_weapon'] },
    Weapon: { weapon_class: ['OneHandAxe'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractOneHandWeapon',
      'AbstractOneHandAxe',
    ],
    tags: ['default', 'weapon', 'onehand', 'axe', 'one_hand_weapon'],
  },
  AbstractOneHandMace: {
    extends: 'AbstractOneHandWeapon',
    Base: { tag: ['mace', 'one_hand_weapon'] },
    Weapon: { weapon_class: ['OneHandMace'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractOneHandWeapon',
      'AbstractOneHandMace',
    ],
    tags: ['default', 'weapon', 'onehand', 'mace', 'one_hand_weapon'],
  },
  AbstractSceptre: {
    extends: 'AbstractOneHandWeapon',
    Base: { tag: ['sceptre', 'one_hand_weapon'] },
    Weapon: { weapon_class: ['Sceptre'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractOneHandWeapon',
      'AbstractSceptre',
    ],
    tags: ['default', 'weapon', 'onehand', 'sceptre', 'one_hand_weapon'],
  },
  AbstractOneHandSword: {
    extends: 'AbstractOneHandWeapon',
    Base: { tag: ['sword', 'one_hand_weapon'] },
    Weapon: { weapon_class: ['OneHandSword'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractOneHandWeapon',
      'AbstractOneHandSword',
    ],
    tags: ['default', 'weapon', 'onehand', 'sword', 'one_hand_weapon'],
  },
  AbstractOneHandSwordThrusting: {
    extends: 'AbstractOneHandSword',
    Weapon: { weapon_class: ['OneHandSwordThrusting'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractOneHandWeapon',
      'AbstractOneHandSword',
      'AbstractOneHandSwordThrusting',
    ],
    tags: ['default', 'weapon', 'onehand', 'sword', 'one_hand_weapon'],
  },
  AbstractWand: {
    extends: 'AbstractOneHandWeapon',
    Base: { tag: ['wand', 'ranged', 'one_hand_weapon'] },
    Weapon: { weapon_class: ['Wand'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractOneHandWeapon',
      'AbstractWand',
    ],
    tags: ['default', 'weapon', 'onehand', 'wand', 'ranged', 'one_hand_weapon'],
  },
  AbstractTwoHandWeapon: {
    extends: 'AbstractWeapon',
    Base: { tag: ['twohand'] },
    Sockets: {
      socket_info: ['1:1:50 2:1:120 3:2:100 4:25:30 5:35:5 6:50:1'],
    },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractTwoHandWeapon',
    ],
    tags: ['default', 'weapon', 'twohand'],
  },
  AbstractBow: {
    extends: 'AbstractTwoHandWeapon',
    Base: { tag: ['bow', 'ranged', 'two_hand_weapon'] },
    Weapon: { weapon_class: ['Bow'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractTwoHandWeapon',
      'AbstractBow',
    ],
    tags: ['default', 'weapon', 'twohand', 'bow', 'ranged', 'two_hand_weapon'],
  },
  AbstractFishingRod: {
    extends: 'AbstractTwoHandWeapon',
    Base: { remove_tag: ['weapon'], tag: ['fishing_rod'] },
    Weapon: { weapon_class: ['FishingRod'] },
    Sockets: {
      socket_info: ['1:1:50 2:1:120 3:2:100 4:25:30 5:9999:20 6:9999:5'],
    },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractTwoHandWeapon',
      'AbstractFishingRod',
    ],
    tags: ['default', 'twohand', 'fishing_rod'],
  },
  AbstractStaff: {
    extends: 'AbstractTwoHandWeapon',
    Base: { tag: ['staff', 'two_hand_weapon'] },
    Weapon: { weapon_class: ['Staff'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractTwoHandWeapon',
      'AbstractStaff',
    ],
    tags: ['default', 'weapon', 'twohand', 'staff', 'two_hand_weapon'],
  },
  Staff1: {
    extends: 'AbstractStaff',
    Sockets: {
      socket_info: ['1:1:50 2:1:120 3:2:100 4:9999:30 5:9999:20 6:9999:5'],
    },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractTwoHandWeapon',
      'AbstractStaff',
      'Staff1',
    ],
    tags: ['default', 'weapon', 'twohand', 'staff', 'two_hand_weapon'],
  },
  AbstractTwoHandAxe: {
    extends: 'AbstractTwoHandWeapon',
    Base: { tag: ['axe', 'two_hand_weapon'] },
    Weapon: { weapon_class: ['TwoHandAxe'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractTwoHandWeapon',
      'AbstractTwoHandAxe',
    ],
    tags: ['default', 'weapon', 'twohand', 'axe', 'two_hand_weapon'],
  },
  AbstractTwoHandMace: {
    extends: 'AbstractTwoHandWeapon',
    Base: { tag: ['mace', 'two_hand_weapon'] },
    Weapon: { weapon_class: ['TwoHandMace'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractTwoHandWeapon',
      'AbstractTwoHandMace',
    ],
    tags: ['default', 'weapon', 'twohand', 'mace', 'two_hand_weapon'],
  },
  AbstractTwoHandSword: {
    extends: 'AbstractTwoHandWeapon',
    Base: { tag: ['sword', 'two_hand_weapon'] },
    Weapon: { weapon_class: ['TwoHandSword'] },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractTwoHandWeapon',
      'AbstractTwoHandSword',
    ],
    tags: ['default', 'weapon', 'twohand', 'sword', 'two_hand_weapon'],
  },
  TwoHandSword1: {
    extends: 'AbstractTwoHandSword',
    Sockets: {
      socket_info: ['1:1:50 2:1:120 3:2:100 4:9999:30 5:9999:20 6:9999:5'],
    },
    inheritance: [
      'Item',
      'Equipment',
      'AbstractWeapon',
      'AbstractTwoHandWeapon',
      'AbstractTwoHandSword',
      'TwoHandSword1',
    ],
    tags: ['default', 'weapon', 'twohand', 'sword', 'two_hand_weapon'],
  },
} as MetaDataMap;
