language: node_js
before_install:
  - yarn global add greenkeeper-lockfile@1
cache:
  yarn: true
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn run lint
  - yarn run format:check
  - yarn run test:ci
  - yarn run coveralls
  - yarn run build